# -*- coding: utf-8 -*-
"""0_EDA_Venkata_Sai_Sri.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16yH_Dhg081ygwKkDo8l5EcYGpQv7gg2p
"""

import pandas as pd

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

covid = pd.read_csv("WHO-COVID-19-global-data.csv")
covid.head()

covid.info()

covid.shape

covid.isnull().sum()

covid.isnull().sum()/covid.shape[0]*100

"""**Individual Column Description**"""

covid.columns

covid.nunique()

"""In the above data set we 1061 unique values in "date_reported", and we have 134 unique country and country codes.

**EDA**
"""

sns.countplot(covid['WHO_region'])
plt.show()

covid['WHO_region'].value_counts()

sns.heatmap(covid.corr(),annot=True)
plt.show()

from pandas_profiling import ProfileReport

profile = ProfileReport(covid, title="Pandas Profiling Report")

profile.to_notebook_iframe()

profile.to_file("your_report.html")